### ISSUE TITLE
Possible Infinite Loop

### ISSUE THREAD

**Issue by scastria** [Placekey/placekey-py#26]
https://github.com/Placekey/placekey-py/blob/faca8db46068dda9393b05984dbe7c63ec31209e/placekey/api.py#L267

Our account/apikey was locked out today due to making too many requests in 1 day.  We then started seeing some of our applications hang.  We traced it down to the line of code referenced above.  It seems to go into an infinite loop for as long as 429 response code is returned.  If our account is locked out for 1 day, for example, that means this code loops continually making calls to placekey for maybe 1 day (not sure how you guys perform your rate limiting calculations).  For example, if we make our entire day's allocations of calls in 1 hour, then we would have to wait 23 hours until our account is unlocked which means this code will loop for 23 hours.  A library should not hang for 23 hours so I think this is a bug.

**Comment by jarredSafegraph** [comment]
Hey Shawn, Thanks for raising this. It looks like the original implementation did not account for the 429 coming from a hitting an upper limit. The fix is in the queue and will be applied and released ASAP. 

Context: [PR Adding Mechanism](https://github.com/Placekey/placekey-py/pull/3#discussion_r523270512)

**Comment by jarredSafegraph** [comment]
Please find the fix in 0.0.13 at https://pypi.org/project/placekey/
